config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:omniauth_callbacks => "omni_auth"}
 
  root 'words#random'
  get '/review' => "words#review"
  get '/rank' => "home#rank"
  resources :words do
    get :search_name, on: :collection
    post :saveall, on: :collection
  end
  namespace :admin do
    resources :words
    resources :users
    resources :word_documents
    resources :tags
  end

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
end

app/controllers/admin/tags_controller.rb
class Admin::TagsController < Admin::BaseController
  def index
    @tags = Tag.page(params[:page]).per(7)
    respond_to do |format|
      format.html { render action: 'index' }
      format.json { render json: @tags.to_json }
    end
  end

  def new
    @tag = Tag.new
    render "new"
  end

  def create
    @tag = Tag.new(params[:tag].permit(:name))
    respond_to do |format|
      if @tag.save
        format.html { redirect_to admin_tags_path, notice: 'Tag was successfully created' }
        format.json { head :no_content, json: @tag.to_json }
      else
        format.html { render action: 'new' }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy
    redirect_to admin_tags_path
  end

end

app/helpers/admin/tags_helper.rb
module Admin::TagsHelper
end

app/views/admin/tags/index.slim
h3 = t("navbar.tags")
= link_to "New", new_admin_tag_path, :class => "btn btn-primary"
table.table.table-striped
  thead
    tr
      th = t("tag.label.name")
      th created_at
      th
  tbody
    - @tags.each do |tag|
      tr
        td = tag.name
        td = tag.created_at.strftime("%d %b %Y %l:%M %p") if tag.created_at
        td = button_to "Destroy", admin_tag_url(tag), :method => :delete, :class => "btn btn-small btn-success"
= paginate @tags

app/views/admin/tags/new.slim
h3 = t("navbar.tags")
= form_for @tag, :html =>  {:role => "form"}, :url => admin_tags_path  do |f|
  - @tag.errors.full_messages.each do |msg|
    .alert.alert-danger
      p = msg
  div.form-group
    label
    = f.text_field :name, :class => "form-control", :placeholder => "Enter tag"
  = f.submit "Save", :class => "btn btn-default"