config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:omniauth_callbacks => "omni_auth"}
 
  root 'words#random'
  get '/review' => "words#review"
  get '/rank' => "home#rank"
  resources :words do
    get :search_name, on: :collection
    post :saveall, on: :collection
  end
  namespace :admin do
    resources :words
    resources :users
    resources :word_documents
    resources :tags
  end

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/word.rb
class Word < ActiveRecord::Base
  belongs_to :user
  belongs_to :tag
  belongs_to :tagged_user, :class_name => User, :foreign_key => :tag_created_by
  
  scope :tagged, -> { where("tag_id IS NOT NULL") }
  scope :untagged, -> { where("tag_id IS NULL") }
  
  validates_uniqueness_of :name
  
  def as_json(options={})
    if self.tag
      { name: self.name, tag: self.tag.name }
    end
  end

end

app/controllers/admin/words_controller.rb
class Admin::WordsController < Admin::BaseController
  def index
    @q = Word.search(params[:q])
    @words = @q.result(distinct: true).page(params[:page]).per(7)
    respond_to do |format|
      format.html { render action: 'index' }
      format.json { render json: @words.to_json }
    end
  end

  def destroy
    @word = Word.find(params[:id])
    @word.destroy
    redirect_to admin_words_path
  end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController

  before_filter :authenticate_user!, :except => [:index]

  def random
    random_number = rand(Word.untagged.count)
    @words = Word.untagged.limit(50).offset(random_number).all
    @word_search = Word.new
    @tags = Tag.pluck(:name, :id)
    respond_to do |format|
      format.html { render action: 'random' }
    end
  end

  def saveall
    word_list = params[:word_list][:word_list].values
    tagged_word_list = word_list.select { |word| !word[:tag_id].blank? }
    tagged_word_list.each do |word|
      w = Word.find(word[:word_id])
      puts w.update_attributes({:tag_id => word[:tag_id].to_i, :tag_created_by => current_user.id})
    end
    redirect_to root_path, :notice => "You have successfully tagged #{tagged_word_list.count} words"
  end

  def show
    @word = Word.find(params[:id])
    @tags = Tag.pluck(:id, :name)
    @word_search = Word.new

    respond_to do |format|
      format.html { render action: 'random' }
    end
  end

  def search_name
    @word = Word.where(name: params[:word][:name]).last
    if @word
      redirect_to word_path(@word)
    else
      redirect_to root_path, :notice => "Could not find ''#{params[:word][:name]}'"
    end
  end

  def index
    @words = Word.includes(:tag, :tagged_user).tagged.page(params[:page]).per(15)
    respond_to do |format|
      if params[:search]
        search = Word.untagged.where("name LIKE '%#{params[:term]}%'").collect{ |word| {id: word.id, label: word.name, value: word.name} }
        format.json { render :json => search.to_json }
      else
        format.json { render :json => @words.to_json }
      end
      format.html { render action: 'index' }
    end
  end

  def update
    @word = Word.find(params[:id])
    @tags = Tag.pluck(:id, :name)
    @word_search = Word.new
    return render action: 'random' if params[:word].blank? or params[:word][:tag_id].blank?
    params[:word][:tag_created_by] = current_user.id
    @word.update_attributes(params[:word].permit(:tag_id, :tag_created_by))
    redirect_to root_path
  end

  def review
    random_number = rand(Word.tagged.count)
    @word = Word.includes(:tagged_user).tagged.limit(1).offset(random_number).first
    @tags = Tag.pluck(:id, :name)
    respond_to do |format|
      format.html { render action: 'review' }
    end
  end
end

app/helpers/admin/words_helper.rb
module Admin::WordsHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/words/index.slim
.more-padding
  h3.word_heading
    = t("navbar.words") 
    span.badge = Word.tagged.count.to_s
  table.table
    thead
      tr
        th Word
        th Tag
        th Tagged by
    tbody
      - @words.each do |word|
        - user = word.tagged_user ? word.tagged_user : nil
        tr
          td = word.name
          td = word.tag.name if word.tag
          td = user.name if(user && user.name)

  = paginate @words

app/views/words/random.slim
- if @words
  .more-padding
    h3 Select Word with parts of speech
    = form_for :word_list, :role => "form", :url => saveall_words_path, :method => :post do |f|
      table.table
        - i = 0
        - @words.each do |word|
          tr
            td = word.name
            = f.hidden_field "word_list[#{i}]word_id", :value => word.id
            td
              .form-group
                = f.select "word_list[#{i}]tag_id", @tags, {:include_blank => "Select parts of speech"},  {:class => "form-control"}
            - i+=1
      div.center-aligned
        = link_to "Skip", root_path, :class => "btn btn-danger"
        = f.submit "Save", :class => "btn btn-success"
- else
  p.bg-info.padding15
    |All words are tagged by users. If you want to review words. click 
    a href="/review" Review

app/views/words/review.slim
- if @word
  .more-padding
    h3 = t("word.review_word")
    h2 = @word.name
    hr
    = form_for @word, :html => {:role => "form", :url => word_path(@word.id), :method => :put}  do |f|
      - @tags.each do |tag|
        div.radio
          label
           = f.radio_button :tag_id, tag[0]
           = tag[1]
      hr
      div.center-aligned
        = link_to "Skip", review_path, :class => "btn btn-danger"
        = f.submit "Save", :class => "btn btn-success"
		== render :partial=>'shared/disqus.slim'
- else
  p.bg-info.padding15 No more words to review