config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:omniauth_callbacks => "omni_auth"}
 
  root 'words#random'
  get '/review' => "words#review"
  get '/rank' => "home#rank"
  resources :words do
    get :search_name, on: :collection
    post :saveall, on: :collection
  end
  namespace :admin do
    resources :words
    resources :users
    resources :word_documents
    resources :tags
  end

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/word_document.rb
class WordDocument < ActiveRecord::Base
  mount_uploader :word_list_file, WordListFileUploader
  validates_presence_of :word_list_file
  belongs_to :user

  after_save do
    WordParser.new(self).parse_and_save unless processed?
  end
end

app/controllers/admin/word_documents_controller.rb
class Admin::WordDocumentsController <  Admin::BaseController

  def index
    @word_documents = WordDocument.page(params[:page]).per(7)
    respond_to do |format|
      format.html { render action: 'index' }
      format.json { render json: @word_documents.to_json }
    end
  end

  def new
    @word_document = WordDocument.new
    render "new"
  end

  def create
    @word_document = WordDocument.new(params[:word_document].permit(:user_id, :word_list_file))
    respond_to do |format|
      if @word_document.save
        format.html { redirect_to admin_word_documents_path, notice: 'Document was successfully created' }
        format.json { head :no_content, json: @word_document.to_json }
      else
        format.html { render action: 'new' }
        format.json { render json: @word_documents.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @word_document = WordDocument.find(params[:id])
    puts params[:word_document].inspect
    unless @word_document.update_attributes(word_document_update)
      flash[:error] = "Could not make process"
    end
    redirect_to admin_word_documents_path
  end

  def destroy
    @word_document = WordDocument.find(params[:id])
    @word_document.destroy
    redirect_to admin_word_documents_path
  end

  def show
  end

  def word_document_update
    params.require(:word_document).permit(:user_id, :word_list_file, :processed)
  end
end

app/helpers/admin/word_documents_helper.rb
module Admin::WordDocumentsHelper
end

app/views/admin/word_documents/index.slim
h3 Documents uploaded
= link_to "New", new_admin_word_document_path, :class => "btn btn-primary"
table.table.table-striped
  thead
    tr
      th Filename
      th user
      th uploaded at
      th
  tbody
    - @word_documents.each do |word_file|
      tr
        td = link_to File.basename(word_file.word_list_file.url), word_file.word_list_file.url, :_target => "blank"
        td = word_file.user.email if word_file.user
        td = word_file.created_at.strftime("%d %b %Y %l:%M %p")
        //td = button_to "Process", admin_word_document_url(word_file, :word_document => {:processed => true}), :method => :patch, :class => "btn btn-small btn-success"
        td = button_to "Destroy", admin_word_document_url(word_file), :method => :delete, :class => "btn btn-small btn-success"
= paginate @word_documents

app/views/admin/word_documents/new.slim
h3 Upload word document
= form_for @word_document, :html =>  {:multipart => true, :role => "form"}, :url => admin_word_documents_path  do |f|
  - @word_document.errors.full_messages.each do |msg|
    .alert.alert-danger
      p = msg
  = f.hidden_field :user_id, :value => current_user.id
  div.form-group
    label
    = f.file_field :word_list_file
  = f.submit "Upload", :class => "btn btn-default"