config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:omniauth_callbacks => "omni_auth"}
 
  root 'words#random'
  get '/review' => "words#review"
  get '/rank' => "home#rank"
  resources :words do
    get :search_name, on: :collection
    post :saveall, on: :collection
  end
  namespace :admin do
    resources :words
    resources :users
    resources :word_documents
    resources :tags
  end

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/views/layouts/admin.slim
doctype html
html
  head
    title = t('project.name')
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=edge"
    meta name="viewport" content="width=device-width, initial-scale=1"
    == stylesheet_link_tag "application", media: 'all', 'data-turbolinks-track' => true
    == javascript_include_tag "application", 'data-turbolinks-track' => true 
    == csrf_meta_tags

  body
    .navbar.navbar-inverse.navbar-fixed-top role="navigation"
      .container
        .navbar-header
          = link_to t('project.name'), "/", :class => "navbar-brand"
        .collapse.navbar-collapse
          ul.nav.navbar-nav
            li
              = link_to t('navbar.home'), "/"
            li
              = link_to t('navbar.word_document'), admin_word_documents_path
            li
              = link_to t('navbar.words'), admin_words_path
            li
              = link_to t('navbar.users'), admin_users_path
            - if current_user
              li
                = button_to t("navbar.logout"), destroy_user_session_path, method: :delete, :class => "btn btn-link nav-link"
    .container
      == yield

app/views/layouts/application.slim
doctype html
html
  head
    title = t('project.name')
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=edge"
    meta name="viewport" content="width=device-width, initial-scale=1"
    meta http-equiv="Content-Type" content="text/html; charset=utf-8"
    meta name="description" content="Sorkandu, Free corpus tool"
    meta name="keywords" content="tamil,corpus,sorkandu,parts of speech,word classes,tamil words,word list"
    == stylesheet_link_tag "application", media: 'all', 'data-turbolinks-track' => true
    == javascript_include_tag "application", 'data-turbolinks-track' => true 
    = javascript_include_tag "https://www.google.com/jsapi"
    == csrf_meta_tags

  body
    .navbar.navbar-inverse.navbar-fixed-top role="navigation"
      .container
        = image_tag current_user.image, :class => "profile_pic" if current_user
        .navbar-header
          button.navbar-toggle type="button" data-toggle="collapse" data-target=".navbar-collapse"
            span.sr-only Toggle navigation
            span.icon-bar
            span.icon-bar
            span.icon-bar
          = link_to t('project.name'), "/", :class=>"navbar-brand"
        .collapse.navbar-collapse
          ul.nav.navbar-nav
            li
                = link_to t('navbar.home'), "/"
            - if current_user
              li
                = link_to t('navbar.review_words'), review_path
              li
                = link_to t('navbar.tag_words'), words_path
            - if current_user and current_user.admin?
              li.dropdown
                = link_to "Admin <span class='caret'></span>".html_safe, "#", :class => "dropdown-toggle", :"data-toggle" => "dropdown"
                ul.dropdown-menu
                  li
                    = link_to t('navbar.words'), admin_words_path
                  li
                    = link_to t('navbar.word_document'), admin_word_documents_path
                  li
                    = link_to t('navbar.tags'), admin_tags_path
                  li
                    = link_to t('navbar.users'), admin_users_path
            - if current_user
                li.dropdown
                  = link_to (current_user.to_s + "<span class='caret'></span>").html_safe, "#", :class => "dropdown-toggle", :"data-toggle" => "dropdown"
                  ul.dropdown-menu
                    li
                      = link_to "Profile", edit_user_registration_path
                    li
                      = button_to t("navbar.logout"), destroy_user_session_path, method: :delete, :class => "btn btn-link nav-link"

    .container
      - if notice or alert
        .alert.alert-danger
          p = notice
          p = alert
      == yield
      javascript:
        google.load("elements", "1", {
            packages: "transliteration"
        });

        function onLoad() {
            var options = {
                sourceLanguage: google.elements.transliteration.LanguageCode.ENGLISH,
                destinationLanguage: [google.elements.transliteration.LanguageCode.TAMIL],
                shortcutKey: 'ctrl+g',
                transliterationEnabled: true
            };

            var control = new google.elements.transliteration.TransliterationControl(options);
            control.makeTransliteratable(['word_search_tr']);
        }
        google.setOnLoadCallback(onLoad);